name: Echo Secret

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering of the workflow.

jobs:
  echo_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo secret
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: |
          # Echoing in a controlled way to avoid leaking to logs
          echo "TEST_TOKEN=${TEST_TOKEN}"
