name: Process Repositories in Partitions

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  partitioner:
    name: Prepare Repository Partitions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
      - name: Set hardcoded matrix
        id: set-matrix
        run: |
          # Hardcoded matrix definition as a dictionary
          MATRIX='{"include":[{"partition":0,"repos":["org/repo1","org/repo2","org/repo3"]},{"partition":1,"repos":["org/repo4","org/repo5","org/repo6"]},{"partition":2,"repos":["org/repo7","org/repo8"]}]}'
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          
  worker:
    name: Process Partition ${{ matrix.partition }}
    needs: partitioner
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.partitioner.outputs.matrix) }}
      fail-fast: false  # Continue other jobs even if one fails
      
    steps:
      - name: Process repositories
        run: |
          echo "Processing repositories in partition ${{ matrix.partition }}"
          
          # Loop through each repository in this partition
          for repo in ${{ join(matrix.repos, ' ') }}; do
            echo "Processing repo: $repo"
          done
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-partition-${{ matrix.partition }}
          path: .
          retention-days: 7
