name: Process Repositories in Partitions

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  partitioner:
    name: Prepare Repository Partitions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
      - name: Set hardcoded matrix
        id: set-matrix
        run: |
          # Hardcoded matrix definition with 3 partitions
          MATRIX='{"partition":[0,1,2],"repos":[["org/repo1","org/repo2","org/repo3"],["org/repo4","org/repo5","org/repo6"],["org/repo7","org/repo8"]]}'
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          
  worker:
    name: Process Partition ${{ matrix.partition }}
    needs: partitioner
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.partitioner.outputs.matrix) }}
      fail-fast: false  # Continue other jobs even if one fails
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Process repositories
        run: |
          echo "Processing repositories in partition ${{ matrix.partition }}"
          
          # Loop through each repository in this partition
          for repo in ${{ join(matrix.repos, ' ') }}; do
            echo "Processing $repo..."
            
            # Your actual processing logic here
            # For example:
            # - Clone repository
            # - Run analysis
            # - Generate reports
            
            # Simulate some work
            sleep 2
            
            echo "Finished processing $repo"
          done
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results-partition-${{ matrix.partition }}
          path: ./results/
          retention-days: 7
