name: Process Repositories in Partitions

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  partitioner:
    name: Split Repositories into Chunks
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Split repositories into partitions
        id: create-matrix
        run: |
          # Define list of repositories (in real world, could come from API, file, etc.)
          REPOS=("org/repo1" "org/repo2" "org/repo3" "org/repo4" "org/repo5" "org/repo6" "org/repo7" "org/repo8")
          
          # Define number of partitions
          PARTITIONS=3
          
          # Create partitioned chunks in JSON format for GitHub Actions matrix
          python -c "
          import json, math
          repos = ${REPOS[@]/#/\"}
          repos = [r + '\"' for r in repos]
          partitions = $PARTITIONS
          chunk_size = math.ceil(len(repos) / partitions)
          chunks = [repos[i:i + chunk_size] for i in range(0, len(repos), chunk_size)]
          matrix = {'partition': list(range(len(chunks))), 'repos': chunks}
          print(f'::set-output name=matrix::{json.dumps(matrix)}')
          "
          
  worker:
    name: Process Partition ${{ matrix.partition }}
    needs: partitioner
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.partitioner.outputs.matrix) }}
      fail-fast: false  # Continue other jobs even if one fails
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Process repositories
        run: |
          echo "Processing repositories in partition ${{ matrix.partition }}"
          
          # Loop through each repository in this partition
          for repo in ${{ join(matrix.repos, ' ') }}; do
            echo "Processing $repo..."
            
            # Your actual processing logic here
            # For example:
            # - Clone repository
            # - Run analysis
            # - Generate reports
            
            # Simulate some work
            sleep 2
            
            echo "Finished processing $repo"
          done
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results-partition-${{ matrix.partition }}
          path: ./results/
          retention-days: 7
